config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  post '/availabilities', to: 'availabilities#create'

  resources :spaces, :users

  root 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability.rb
class Availability < ActiveRecord::Base
  validates_presence_of :space_id, :date

  def self.populate_available_dates(space_id, start_date, end_date)
    dates_array = DateRange.range(start_date, end_date)
    dates_array.each do |date|
      Availability.create(space_id: space_id, date: date)
    end
  end

end

app/models/date_range.rb
class DateRange

  DATE_FORMAT = "%d/%m/%Y"

  def self.range(start_date, end_date)
    range = (format_date(start_date)..format_date(end_date)).map { |date|
      date.strftime(DATE_FORMAT)
    }
    range.slice!(-1)
    range
  end

  private_class_method

  def self.format_date(date)
    Date::strptime(date, DATE_FORMAT)
  end

end

app/models/password.rb
class Password

  def self.check_password(user, password)
    stored_password = User.where(username: user).pluck(:password).first
    return false if stored_password.nil?

    valid_password = validate(stored_password)
    valid_password == password
  end

  def self.create(password)
    BCrypt::Password.create(password)
  end

  def self.validate(password)
    BCrypt::Password.new(password)
  end

end

app/models/space.rb
class Space < ActiveRecord::Base
  validates_presence_of :name, :description, :price, :user_id

  belongs_to :user
  has_many :availability
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :forename, :surname, :username, :password, :email
  validates_uniqueness_of :username, :email
  has_many :availability
  has_many :space

  def self.return_user_info(user_id)
    User.find_by(id: user_id)
  end

  def self.return_user_id(username)
    User.find_by(username: username).id
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
  def new

  end

  def create
    redirect_to :controller => 'spaces', :action => 'index'
  end

end

app/controllers/sessions_controller.rb
require 'bcrypt'

class SessionsController < ApplicationController
  def new
  end

  def create
    if Password.check_password(params[:session][:username],
      params[:session][:password])
      session[:user_id] = User.return_user_id(params[:session][:username])
      redirect_to :controller => 'spaces', :action => 'index'
    else
      flash[:error] = 'Incorrect Username or Password'
      render 'new'
    end
  end

  def destroy
    session.clear
    redirect_to :controller => 'users', :action => 'create' 
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  def new
  end

  def create
    Space.create(
      name: params[:name],
      description: params[:description],
      price: params[:price],
      user_id: session[:user_id])
    redirect_to :action => 'index'
  end

  def show
    @dates = Space.left_outer_joins(:availability)
                             .where(spaces: { id: params[:id] })
                             .select('spaces.*', 'availabilities.date')
                             .pluck(:date)
    @space = Space.find_by(id: params[:id])
    render 'show'
  end

  def index
    @spaces = Space.all
    @space = Space.find_by(id: params[:id])
    render 'index'
  end
end

app/controllers/users_controller.rb
require 'bcrypt'

class UsersController < ApplicationController
  def new
  end

  def create
    hash_password = Password.create(params[:password])
    newuser = User.create(email: params[:email],
                forename: params[:forename],
                surname: params[:surname],
                username: params[:username],
                password: hash_password)
    if newuser.errors.any?
      flash[:error] = newuser.errors.full_messages.first
      redirect_to ('/users/new') and return
    end
    session[:user_id] = User.return_user_id(params[:username])
    redirect_to :controller => 'spaces', :action => 'index'
  end

  def index
    redirect_to :controller => 'users', :action => 'new'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Makersbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_menu.html.erb
<div style="text-align: right; padding-right: 3rem">

  <nav>
  <% links = {
  'Sign up' => '/users/new',
  'Log in' => '/login',
  'Add your space' => '/spaces/new',
  'View spaces' => '/spaces'}
  links.each do |key, value|
  unless request.fullpath == value %>
    <a href="<%=value%>"><%=key%></a> |
  <% end %>
<% end %>
<%= link_to "Log out", logout_path, :method => :delete %>
  <% if !!session[:user_id] %>
  Hi, <%= User.return_user_info(session[:user_id])[:forename] %>!
  <% end %>
  </nav>
  </div>

app/views/spaces/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Spaces</title>
    <link rel="stylesheet" type="text/css" href="showlisting.css">
    <link rel="stylesheet" href="../../assets/stylesheets/spaces.css">
  </head>
  <body>
    <%= render 'shared/menu' %>
    <div class="container">
      <div class="top1"></div>
      <div class="top2"><h1 class="heading">MakersBnB</h1> </div>
      <div class="top3"></div>

      <% @spaces.each.with_index do |space, index| %>
      <div id="card<%= index + 1%>" class="cardbg">
        <div class="imagecontainer"><%= link_to image_tag("https://source.unsplash.com/collection/416011/300x300"), space_path(space.id) %></div>
          <div class="placename">
            <p class="textname"><%= link_to "#{space.name}", space_path(space.id) %></p>
          </div>
          <div class="price">
            <p class="textprice"><%= "£#{space.price} per night" %></p>
          </div>
          <div class="placedescription">
            <p class="textdescription"><%= "#{space.description}" %></p>
          </div>
      </div>
      <% end %>

  </body>
</html>

app/views/spaces/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>List a space</title>
    <link rel="stylesheet" href="../../assets/stylesheets/users.css">
  </head>
  <body>

<%= render 'shared/menu' %>


<% provide(:title, "List a Space") %>

<div class="top1"></div>
<div class="top2"><h1 class="heading">List a space</h1> </div>
<div class="top3"></div>

  <div class="top1"></div>
  <div class="top2">

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @space, url: {action: "create"}, local: true do |f| %>

      <p><%= f.text_field :name, class: 'form-control', placeholder: 'name of place' %></p>

      <p><%= f.text_area :description, class: 'form-control', placeholder: 'description', cols: 18, rows: 3%></p>

      <p><%= f.text_field :price, class: 'form-control', placeholder: 'Price per night (£)' %></p>

      <p><%= f.label :Availability %></p>

      <p><%= f.date_field :start_date, class: 'form-control', placeholder: 'Start date' %></p>

      <p><%= f.date_field :end_date, class: 'form-control', placeholder: 'End date' %></p>

      <p><%= f.submit "Submit", class: "btn btn-primary" %></p>
    <% end %>

  </div>
</div>
</div>
<div class="top3"></div>
</body>
</html>

app/views/spaces/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Spaces</title>
    <link rel="stylesheet" type="text/css" href="showlisting.css">
    <link rel="stylesheet" href="../../assets/stylesheets/spaces.css">
  </head>
  <body>
    <%= render 'shared/menu' %>
    <div class="container">
      <div class="top1"></div>
      <div class="top2"><h1 class="heading">MakersBnB</h1> </div>
      <div class="top3"></div>

    <div class="cardbg">
      <div class="imagecontainer"><img src="https://source.unsplash.com/collection/416011/300x300" ></div>
        <div class="placename">
          <p class="textname"><%= "#{@space[:name]}" %></p>
        </div>
        <div class="price">
          <p class="textprice"><%= "£#{@space[:price]} per night" %></p>
        </div>
        <div class="placedescription">
          <p class="textdescription"><%= "#{@space[:description]}" %></p>
          <p class="textdescription">Dates available:</p>
              <%= form_with model: @availability, url: {action: "create"}, local: true do |f| %>
              <% @dates.each do |date| %>
                <p class="textdescription"><%= f.radio_button :availability, date %>
                  <%= date.strftime("%A, %e %B %Y") %></p>
              <% end %>
              <p class="buttondescription"><%= f.submit "Book", class: "btn btn-primary" %></p>
            <% end %>
          </div>
        </div>
</body>
</html>

app/views/spaces/show_mockup.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Spaces</title>
    <link rel="stylesheet" type="text/css" href="showlisting.css">
    <link rel="stylesheet" href="../../assets/stylesheets/spaces.css">
  </head>
  <body>
    <%= render 'shared/menu' %>
    <h1>Look at all the places!</h1>
    <div class="container">
      <div class="top1"><a class="navback" href="LASTPAGE"><img src="arr_backward.png"></a></div>
      <div class="top2"><h1 class="heading">MakersBnB</h1> </div>
      <div class="top3"><a class="navnext" href="NEXTPAGE"><img src="arr_forward.png"></a></div>

      <% @spaces.each.with_index do |space, index| %>
      <div id="card<%= index + 1%>" class="cardbg">
        <div class="imagecontainer">
<img src="https://source.unsplash.com/collection/416011/300x300" id=#cardimg1">
    </div>
          <div class="placename">
            <p class="textname"><%= "#{space.name}" %></p>
          </div>
          <div class="price">
            <p class="textprice"><%= "£#{space.price} per night" %></p>
          </div>
          <div class="placedescription">
            <p class="textdescription"><%= "#{space.description}" %></p>
            <%= @dates %>
          </div>
      </div>
      <% end %>

  </body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Sign up</title>
    <link rel="stylesheet" href="../../assets/stylesheets/users.css">
  </head>
  <body>

    <%= render 'shared/menu' %>

    <% provide(:title, "Sign up") %>

    <div class="container">

    <div class="top1"></div>
    <div class="top2"><h1 class="heading">Sign up</h1> </div>
    <div class="top3"></div>

      <div class="top1"></div>
      <div class="top2">

        <%= form_with model: @user, url: {action: "create"}, local: true do |f| %>

        <p><%= f.email_field :email, class: 'form-control', placeholder: 'Email' %></p>

        <p><%= f.text_field :forename, class: 'form-control', placeholder: 'First name'  %></p>
        
        <p><%= f.text_field :surname, class: 'form-control', placeholder: 'Last name' %></p>

        <p><%= f.text_field :username, class: 'form-control', placeholder: 'Username' %></p>

        <p><%= f.password_field :password, class: 'form-control', placeholder: 'Password' %></p>

        <p><%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Password' %></p>

        <%= f.submit "Sign up", class: "btn btn-primary" %>
    <% end %>
    <br>
    <%= flash[:error] %>
  </div>
</div>

app/views/welcome/index.html.erb
<% provide(:title, "Sign up") %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @user, url: {action: "create"}, local: true do |f| %>

      <%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>

      <%= f.email_field :forename, class: 'form-control', placeholder: 'First name'  %>

      <%= f.email_field :surname, class: 'form-control', placeholder: 'Last name' %>

      <%= f.text_field :username, class: 'form-control', placeholder: 'Username' %>

      <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>

      <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>